export const ROUTES = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  DATA_STACK: 'DATA_STACK',
  DEVICE_ID_SCREEN: 'DEVICE_ID_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  MAP_SCREEN: 'MAP_SCREEN',
  BILGE_SCREEN: 'BILGE_SCREEN',
  BATERY_SCREEN: 'BATERY_SCREEN',
  ALERTS_SCREEN: 'ALERTS_SCREEN',
  DETAILS_SCREEN: 'DETAILS_SCREEN',
  NOT_FOUND: 'NOT_FOUND',
  EXPIRED_SUBSCRIPTION: 'EXPIRED_SUBSCRIPTION',
  NO_INTERNET: 'NO_INTERNET',
};
